export default {
  "data": [
    {
      "id": "402881a760c3e2760160c3e2d96a0000",
      "shipCompany": "COSCO",
      "route": "中东",
      "firstStartPort": "黄埔",
      "firstWharfRemark": "乌冲/大码头",
      "secondStartPort": "南沙",
      "secondEndPort": "沙迦",
      "secondTransitPort": "迪拜",
      "currency": "USD",
      "weightLimitDescription": null,
      "surchargeRemark": "测试附加费",
      "bargeETC": 1514433600000,
      "bargeETD": 1514523600000,
      "vesselETC": 1514530800000,
      "vesselETD": 1514635200000,
      "schedule": "18",
      "routeCode": "AWS6",
      "effectiveDate": 1513756800000,
      "expiryDate": 1546131600000,
      "remark": "测试",
      "internalRemark": "内部测试",
      "agencyCompany": "恒通货运",
      "trailerTotal": 0.0,
      "customsTotal": 0.0,
      "storageTotal": 0.0,
      "certificateTotal": 0.0,
      "insuranceTotal": 0.0,
      "usdTotal": 1114.0,
      "rmbTotal": 3162.0,
      "containerTypeRouteServiceVOList": [
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "20GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 650.0,
          "quantity": 1,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "45HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 1150.0,
          "quantity": null,
          "status": null
        }],
      "surchargeRouteServiceVOList": [
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "THC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 875.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "THC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "THC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "THC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1675.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "ORC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "ORC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "ORC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "ORC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 2250.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "PCC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 62.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "PCC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "PCC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "PCC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "CIF_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "CIF_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "CIF_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "CIF_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WRS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 24.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WRS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WRS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WRS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 58.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 150.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 400.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "OWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "OWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "OWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "OWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "DOC",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "T/R",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "ENS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AMS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AFR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "SEAL",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "EIR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "VGM",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 25.0,
          "status": null
        }],
      "trailerQuoteTmpVOList": null,
      "customsQuoteTmpVOList": null,
      "storageQuoteTmpVOList": null,
      "certificateQuoteTmpVO": null,
      "haveBarge": false
    },
    {
      "id": "402881a760c444ec0160c44953ee0003",
      "shipCompany": "COSCO",
      "route": "南非",
      "firstStartPort": "黄埔",
      "firstWharfRemark": "乌冲/大码头",
      "secondStartPort": "南沙",
      "secondEndPort": "墨西哥",
      "secondTransitPort": "迪拜",
      "currency": "USD",
      "weightLimitDescription": null,
      "surchargeRemark": "测试附加费",
      "bargeETC": 1514433600000,
      "bargeETD": 1514523600000,
      "vesselETC": 1514530800000,
      "vesselETD": 1514635200000,
      "schedule": null,
      "routeCode": null,
      "effectiveDate": 1511168400000,
      "expiryDate": 1514642400000,
      "remark": null,
      "internalRemark": null,
      "agencyCompany": "恒通货运",
      "trailerTotal": 0.0,
      "customsTotal": 0.0,
      "storageTotal": 0.0,
      "certificateTotal": 0.0,
      "insuranceTotal": 0.0,
      "usdTotal": 1114.0,
      "rmbTotal": 3162.0,
      "containerTypeRouteServiceVOList": [
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "20GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 650.0,
          "quantity": 1,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "45HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 1150.0,
          "quantity": null,
          "status": null
        }],
      "surchargeRouteServiceVOList": [
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "THC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 875.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "THC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "THC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "THC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1675.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "ORC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "ORC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "ORC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "ORC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 2250.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "PCC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 62.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "PCC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "PCC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "PCC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "CIF_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "CIF_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "CIF_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "CIF_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WRS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 24.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WRS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WRS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WRS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 58.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 150.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 400.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "OWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "OWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "OWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "OWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "DOC",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "T/R",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "ENS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AMS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AFR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "SEAL",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "EIR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "VGM",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 25.0,
          "status": null
        }],
      "trailerQuoteTmpVOList": null,
      "customsQuoteTmpVOList": null,
      "storageQuoteTmpVOList": null,
      "certificateQuoteTmpVO": null,
      "haveBarge": false
    },
    {
      "id": "402881a760c444ec0160c44953ef0004",
      "shipCompany": "COSCO",
      "route": "欧洲",
      "firstStartPort": "黄埔",
      "firstWharfRemark": "乌冲/大码头",
      "secondStartPort": "南沙",
      "secondEndPort": "意大利",
      "secondTransitPort": "上海",
      "currency": "USD",
      "weightLimitDescription": null,
      "surchargeRemark": "测试附加费",
      "bargeETC": 1514433600000,
      "bargeETD": 1514523600000,
      "vesselETC": 1514530800000,
      "vesselETD": 1514635200000,
      "schedule": null,
      "routeCode": null,
      "effectiveDate": 1511168400000,
      "expiryDate": 1514642400000,
      "remark": null,
      "internalRemark": null,
      "agencyCompany": "恒通货运",
      "trailerTotal": 0.0,
      "customsTotal": 0.0,
      "storageTotal": 0.0,
      "certificateTotal": 0.0,
      "insuranceTotal": 0.0,
      "usdTotal": 1114.0,
      "rmbTotal": 3162.0,
      "containerTypeRouteServiceVOList": [
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "20GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 650.0,
          "quantity": 1,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "45HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 1150.0,
          "quantity": null,
          "status": null
        }],
      "surchargeRouteServiceVOList": [
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "THC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 875.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "THC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "THC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "THC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1675.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "ORC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "ORC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "ORC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1850.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "ORC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 2250.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "PCC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 62.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "PCC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "PCC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "PCC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "CIF_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "CIF_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "CIF_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "CIF_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WRS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 24.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WRS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WRS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WRS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 58.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 150.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 400.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "OWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "OWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "OWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "OWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "DOC",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "T/R",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "ENS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AMS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AFR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "SEAL",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "EIR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "VGM",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 25.0,
          "status": null
        }],
      "trailerQuoteTmpVOList": null,
      "customsQuoteTmpVOList": null,
      "storageQuoteTmpVOList": null,
      "certificateQuoteTmpVO": null,
      "haveBarge": false
    },
    {
      "id": "402881ae60d3ee0b0160d3f75c060003",
      "shipCompany": "MAERSK",
      "route": "美加",
      "firstStartPort": "黄埔",
      "firstWharfRemark": "乌冲/大码头",
      "secondStartPort": "南沙",
      "secondEndPort": "意大利",
      "secondTransitPort": "上海",
      "currency": "USD",
      "weightLimitDescription": null,
      "surchargeRemark": "测试附加费",
      "bargeETC": 1514433600000,
      "bargeETD": 1514523600000,
      "vesselETC": 1514530800000,
      "vesselETD": 1514635200000,
      "schedule": null,
      "routeCode": null,
      "effectiveDate": 1511168400000,
      "expiryDate": 1514642400000,
      "remark": null,
      "internalRemark": null,
      "agencyCompany": "恒通货运",
      "trailerTotal": 0.0,
      "customsTotal": 0.0,
      "storageTotal": 0.0,
      "certificateTotal": 0.0,
      "insuranceTotal": 0.0,
      "usdTotal": 1114.0,
      "rmbTotal": 2287.0,
      "containerTypeRouteServiceVOList": [
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "20GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 650.0,
          "quantity": 1,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40GP",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "40HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 950.0,
          "quantity": null,
          "status": null
        },
        {
          "id": null,
          "containerTypeVO": null,
          "routeServiceVO": null,
          "containerTypeName": "45HQ",
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 1150.0,
          "quantity": null,
          "status": null
        }],
      "surchargeRouteServiceVOList": [
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "THC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "THC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1165.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "ORC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 1100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "ORC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 2250.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "PCC_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 62.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "PCC_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "PCC_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "PCC_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 96.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "CIF_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "CIF_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "CIF_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "CIF_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WRS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 24.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WRS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WRS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 48.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WRS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 58.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "WWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 150.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "WWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "WWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "WWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 400.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "20GP",
          "englishName": "OWS_20GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 100.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40GP",
          "englishName": "OWS_40GP",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "40HQ",
          "englishName": "OWS_40HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 200.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": "45HQ",
          "englishName": "OWS_45HQ",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "TUE",
          "price": 300.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "DOC",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "T/R",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "BILL",
          "price": 500.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "ENS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AMS",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "AFR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "USD",
          "unit": "BILL",
          "price": 30.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "SEAL",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "EIR",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 50.0,
          "status": null
        },
        {
          "id": null,
          "createDate": null,
          "modifyDate": null,
          "surchargeVO": null,
          "routeServiceVO": null,
          "sign": null,
          "englishName": "VGM",
          "chineseName": null,
          "operationLineName": null,
          "currency": "RMB",
          "unit": "TUE",
          "price": 25.0,
          "status": null
        }],
      "trailerQuoteTmpVOList": null,
      "customsQuoteTmpVOList": null,
      "storageQuoteTmpVOList": null,
      "certificateQuoteTmpVO": null,
      "haveBarge": false
    }],
  "returnCode": 0
}